"""Export independent Python operators for the MATLAB regression tests.

Run from the repository root: python3 python/export_matlab_full_reference.py
This exports small M=1 and M=5 systems, including the nonlinear RHS/Jacobian
away from steady state. It does not execute or translate the MATLAB code.
"""
from dataclasses import asdict, replace
from pathlib import Path

import numpy as np
from scipy.io import savemat

from cpadynamics import Parameters, FullModel


def main():
    p = replace(Parameters(), geneLength_bp=500, PASposition=300, kEoff_engaged=.05)
    reference = {'parameters': asdict(p), 'source': 'cpadynamics.FullModel; generated by export_matlab_full_reference.py'}
    for m in (1, 5):
        model = FullModel(p, m)
        x = .5+.1*np.sin(np.arange(1, model.size+1))
        state = np.r_[x, p.E_total-model.e_counts@x, p.Pol_total-x.sum()]
        prefix = f'M{m}_'
        reference.update({prefix+'A0': model.a0, prefix+'AE': model.ae,
                          prefix+'R_states': np.asarray(model.r_states),
                          prefix+'RHE_states': np.asarray(model.rhe_states),
                          prefix+'state': state[:, None],
                          prefix+'rhs': model.rhs(0, state)[:, None],
                          prefix+'jacobian': model.jacobian(0, state)})
    destination = Path(__file__).resolve().parents[1]/'tests'/'fixtures'/'full_model_python_reference.mat'
    destination.parent.mkdir(parents=True, exist_ok=True)
    savemat(destination, reference, do_compression=True)
    print(destination)


if __name__ == '__main__':
    main()
